### PR TITLE
Sync with mgechev/revive's master

### PR DESCRIPTION
**Pull request by subham-deepsource**
Changes include:

1. Sync with mgechev/revive's (upstream) master.
2. Bring back parallelization execution of rules which was disabled earlier because of data races. Now that the data races are taken care of, I've reverted my change.
3. Remove `println` used for debugging.

### CODE REVIEW

**Comment by subham-deepsource** [comment]
cc: @srijan-deepsource 

Can you please add @akshit-deepsource as a collaborator so I can add him as a reviewer?

**Comment by srijan-deepsource** [comment]
> cc: @srijan-deepsource
> 
> Can you please add @akshit-deepsource as a collaborator so I can add him as a reviewer?

Done, sir!

**Comment by subham-deepsource** [comment]
> > cc: @srijan-deepsource
> > Can you please add @akshit-deepsource as a collaborator so I can add him as a reviewer?
> 
> Done, sir!

Thanks!

**Review by akshit-deepsource — DISMISSED** [review]

**Comment by subham-deepsource** [comment]
It's such a headache to sign the unsigned commits. Somewhere I messed up with the conflicts, I guess.

**Review by akshit-deepsource — APPROVED** [review]

**Pull request merged**
